name: Github Action sharing - Upload to appcenter  

on:
  push:
    branches:
      - master

jobs:

  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup java 
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Build apk 
        run: ./gradlew assembleRelease
      - name: Setup appcenter-cli
        run: npm install -g appcenter-cli
      - name: Appcenter login
        run: appcenter login --token ${{ secrets.APPCENTER_TOKEN }} --disable-telemetry
      - name: Upload to appcenter
        run: appcenter distribute release --group Collaborators --app ${{ env.APPCNTER_APP_NAME }} --file ./app/build/outputs/apk/release/app-release.apk --disable-telemetry

env:
  APPCNTER_APP_NAME: Weidaicheng/Android-Greeting-George